version: "3"
services:
  php:
    build:
      context: ./env/php
      args:
        - PHP_VERSION=5.6
    container_name: sample.vhost.php
    environment:
      - PHP_HOST=sample.vhost
      - PHP_DIR=~sample.vhost
      - PHP_UPLOAD_MAX_FILESIZE=100M
      - PHP_POST_MAX_SIZE=100M
    volumes:
      - .:/var/www/vhost:rw
      - ./env/php/logs:/var/log/php-fpm-alternative:rw
      - ./env/php/etc:/etc/php/all/fpm:rw
    networks:
      - ggenv.network
    depends_on:
      - sql
  sql:
    image: 'bitnami/mariadb'
    container_name: sample.vhost.sql
    environment:
      - MARIADB_DATABASE=develop
      - MARIADB_USER=develop
      - MARIADB_PASSWORD=secret
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./env/sql:/bitnami/mariadb
    networks:
      - ggenv.network

networks:
  ggenv.network:
    external: true
