version: "3.7"
services:
  php:
    build:
      context: ./env/php
      args:
        - PHP_VERSION=7.2
    container_name: php.sample.vhost
    environment:
      PHP_HOST: sample.vhost
      PHP_DIR: sample.vhost
    volumes:
      - .:/var/www/vhost:rw,delegated
    networks:
      - ggenv.network
    depends_on:
      - sql
  sql:
    image: mysql/mysql-server:5.6
    container_name: sql.sample.vhost
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON --log_bin=ON --socket=/tmp/mysqld.sock
    environment:
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: qweR432!
      MYSQL_ROOT_PASSWORD: qweR432!
      BIND_ADDRESS: 0.0.0.0
    volumes:
      - ggenv.mysql.5.6:/var/lib/mysql:delegated
    networks:
      - ggenv.network

volumes:
  ggenv.mysql.5.6:
    external: true

networks:
  ggenv.network:
    external: true
