version: "3.7"
services:
  php:
    build:
      context: ./env/php
      args:
        PHP_VERSION: 7.2
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    container_name: php.sample.vhost
    environment:
      VHOST_NAME: sample.vhost
    volumes:
      - .:/var/www/vhost:rw,cached
    networks:
      - ggenv.network
    depends_on:
      - sql
  sql:
    image: mysql/mysql-server:5.6
    container_name: sql.sample.vhost
    command: >
      mysqld
      --socket=/tmp/mysqld.sock
      --default-authentication-plugin=mysql_native_password
      --log_bin=ON
      --skip-external-locking
      --skip-innodb
      --default-storage-engine=MyISAM
      --default-tmp-storage-engine=MyISAM
    environment:
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: qweR432!
      MYSQL_ROOT_PASSWORD: qweR432!
      BIND_ADDRESS: 0.0.0.0
    volumes:
      - ggenv.mysql.5.6:/var/lib/mysql:cached
    networks:
      - ggenv.network

volumes:
  ggenv.mysql.5.6:
    external: true

networks:
  ggenv.network:
    external: true
