FROM nginx

# Other environment variables
ENV TIMEZONE Europe/Moscow

# Include specify files
COPY etc/nginx.conf /etc/nginx/nginx.conf
COPY etc/nginx.conf.d /etc/nginx/nginx.conf.d
COPY usr/share /usr/share/nginx
